version: 2
jobs:
  build:
    working_directory: ~/test_tests
    docker:
    - image: gcc:8.2
    steps:
    - checkout
    - run: make re

# version: 2.1
# jobs:
#   build:
#     woking_directory: ~/test_tests
#     steps:
#     - checkout
#     - run: make test
