version: 2.1
jobs:
  build:
    docker:
    - image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run: make test

# version: 2.1
# jobs:
#   build:
#     woking_directory: ~/test_tests
#     steps:
#     - checkout
#     - run: make test
